In [8]:
import numpy as np

In [9]:
arr = np.arange(9).reshape((3, 3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
sh = np.random.shuffle(arr)
arr

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [3]:
QUANTIZATION_LEVEL = 10

In [4]:
c_pos = np.linspace(-5, 5, QUANTIZATION_LEVEL)
c_vel = np.linspace(-5, 5, QUANTIZATION_LEVEL)
p_ang = np.linspace(-1, 1, QUANTIZATION_LEVEL)
p_vel = np.linspace(-5, 5, QUANTIZATION_LEVEL)

In [6]:
A,B,C,D = np.meshgrid(c_pos,c_vel,p_ang,p_vel)

In [7]:
Q = A+B+C+D

In [8]:
Q.shape

(10, 10, 10, 10)