In [1]:
import numpy as np

In [5]:
GRANULARITY = 50
N_ACTIONS = 10

In [6]:
Q_TABLE = np.zeros((GRANULARITY,
                    GRANULARITY,
                    GRANULARITY,
                    GRANULARITY, 
                    N_ACTIONS))

In [7]:
id(Q_TABLE)

140095514754464

In [8]:
my_Q = Q_TABLE.copy()

In [9]:
id(my_Q)

140095514320944

In [25]:
a = np.arange(0,3)

In [26]:
id(a)

139935269251152

In [27]:
b = a

In [28]:
id(b)

139935269251152

In [29]:
c = a.copy()

In [30]:
id(c)

139935269251392

In [31]:
print(a,b,c)

[0 1 2] [0 1 2] [0 1 2]


In [32]:
a[1] = 99

In [33]:
print(a,b,c)

[ 0 99  2] [ 0 99  2] [0 1 2]


In [34]:
b[0] = 100

In [35]:
print(a,b,c)

[100  99   2] [100  99   2] [0 1 2]


In [ ]:
`

In [23]:
def ndim_grid(start,stop, granularity=3):
    # Set number of dimensions
    ndims = len(start)

    # List of ranges across all dimensions
    L = [np.linspace(start[i],stop[i],granularity) for i in range(ndims)]

    # Finally use meshgrid to form all combinations corresponding to all 
    # dimensions and stack them as M x ndims array
    return np.hstack((np.meshgrid(*L))).swapaxes(0,1).reshape(ndims,-1).T

In [24]:
granularity = 2

In [25]:
index_list = ndim_grid([-2, -2,-2,-2],[2,2,2,2],granularity)

In [26]:
index_list

array([[-2., -2., -2., -2.],
       [-2., -2., -2.,  2.],
       [-2., -2.,  2., -2.],
       [-2., -2.,  2.,  2.],
       [-2.,  2., -2., -2.],
       [-2.,  2., -2.,  2.],
       [-2.,  2.,  2., -2.],
       [-2.,  2.,  2.,  2.],
       [ 2., -2., -2., -2.],
       [ 2., -2., -2.,  2.],
       [ 2., -2.,  2., -2.],
       [ 2., -2.,  2.,  2.],
       [ 2.,  2., -2., -2.],
       [ 2.,  2., -2.,  2.],
       [ 2.,  2.,  2., -2.],
       [ 2.,  2.,  2.,  2.]])

In [41]:
coordinate = [1,1,0,1]

In [42]:
index = coordinate * np.array([granularity**3, granularity**2, granularity, 1])

In [43]:
index_list[index.sum().astype(int)]

array([ 2.,  2., -2.,  2.])

In [50]:
a = 5
b = [1,2]
c = zip(b,a)


TypeError: zip argument #2 must support iteration

In [3]:
o ='a'
l = [1,2,3]
arg = [(i, o) for i in l]

In [4]:
arg

[(1, 'a'), (2, 'a'), (3, 'a')]